#!/bin/bash

# $1 is the iteration, $2 is the start node, $3 is the step, $4 is the iteration count

time poetry run python3 -m src.kmxwasm.property \
    --claim $CLAIM --kcfg=../.property/kcfg.$BACKEND.$CONTRACT.$STEP.json \
    --step $3 \
    --iterations $4 \
    --booster \
    --restart \
    --run $2 \
    --bug-report evaluation-loop \
    2>&1 | cat > logs/property.$BACKEND.$CONTRACT.$STEP.$1.log
