#!/bin/bash

# $1 is the iteration, $2 is the start node

time poetry run python3 -m src.kmxwasm.property \
    --kcfg=../.property/kcfg.$BACKEND.$CONTRACT.$STEP.json \
    --booster \
    --bisect-after $2 \
    2>&1 | cat > logs/property.$BACKEND.$CONTRACT.$STEP.$1.log
